[package]
name = "pkuphys-essay"
version = "0.0.2"
authors = ["CL4R3T <https://github.com/CL4R3T>"]
license = "MIT"
description = "Template for writing essays and experiment reports."
entrypoint = "template.typ"
repository = "https://github.com/CL4R3T/pkuphys-essay-typst"
